services:
  - type: web
    name: xdg-benchmarking-dashboard
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn dashboard:server
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0